# Анализ успешно закрытых задач

## Задания :
### 1. Топ-5 фамилий менеджеров по доли успешно закрытых задач
### 2. Собрать фамилии менеджеров у кого показатели отработки задач (% неуспешных задач) по одной из категорий бизнеса хуже, чем в среднем у всех менеджеров по всем категориям.
### 3. Реализовать 2 задание на Python
### 4. Генерация гипотез/идей. По каким открытым/банковским данным можно понять,  что клиент ведет внешнеэкономическую деятельность?

## Подзадача:
### Сгенерировать данные таблиц users, clients и tasks

In [1]:
# Используемые библиотеки

import pandas as pd

In [2]:
# Надстройки

pd.options.display.float_format = "{:,.3f}".format

## Прочитаем наши файлы csv, чтобы создать один большой датафрейм

### Создадим датафрейм df_users из файла users_data.csv

In [3]:
df_users = pd.read_csv('P:/Testing/users_data.csv', sep = ';')

In [4]:
display(df_users)

     USER_ID   LAST_NAME  START_WORK  END_WORK
0          1      Ivanov           8        19
1          2      Petrov           1        10
2          3     Sazonov          21        21
3          4  Molchanova           9        23
4          5      Noskov          20         1
..       ...         ...         ...       ...
495      496   Fedosenko          10        14
496      497  Nikiforova          15        10
497      498   Evdokimov           5        20
498      499     ROMANOV          22         1
499      500  Sidorovkin           5        16

[500 rows x 4 columns]

### Создадим датафрейм df_clients из файла clients_data.csv

In [5]:
df_clients = pd.read_csv('P:/Testing/clients_data.csv', sep = ';')

In [6]:
display(df_clients)

      CLIENT_ID                               NAME        CATEGORY
0             1                         ИП Шолохов    Малый бизнес
1             2                      ООО Звездочка  Средний бизнес
2             3    АО Шарапова, Федосеев и Макаров  Средний бизнес
3             4   РАО Захаров, Чернов и Большакова    Малый бизнес
4             5                      Панфилова Лтд  Средний бизнес
...         ...                                ...             ...
5997       5998      АО Мишина, Елисеев и Шарапова    Малый бизнес
5998       5999                 ИП Шарова Смирнова    Малый бизнес
5999       6000  ИП Зиновьева, Данилова и Голубева    Малый бизнес
6000       6001               ЗАО Капустин Фролова  Средний бизнес
6001       6002              ООО Сорокин-Муравьева    Малый бизнес

[6002 rows x 3 columns]

### Создадим датафрейм df_tasks из файла tasks_data.csv

In [7]:
df_tasks = pd.read_csv('P:/Testing/tasks_data.csv', sep = ',')

In [8]:
display(df_tasks)

,TASK_ID,CLIENT_ID,USER_ID,STATUS,START_DATE,END_DATE
0,3,2159,79,fail,2026-01-13 13:58:20,2026-01-29 18:20:21
1,4,2527,66,success,2026-02-18 10:40:42,2026-02-18 10:47:38
2,5,659,473,fail,2026-01-04 06:34:41,2026-01-24 12:34:14
3,6,764,351,success,2026-01-11 18:00:30,2026-01-28 04:50:16
4,7,3122,396,success,2026-02-17 02:54:07,2026-02-22 10:42:03
...,...,...,...,...,...,...
8997,9000,4035,102,success,2026-01-23 23:20:31,2026-01-31 14:59:51
8998,9001,3970,368,success,2026-01-29 00:56:45,2026-02-12 21:15:21
8999,9002,1941,336,success,2026-01-23 15:50:04,2026-02-20 19:30:40
9000,1,1,1,success,2023-05-01 09:17:00,2023-05-21 17:23:00
9001,2,2,1,fail,2023-05-01 10:19:00,2023-05-21 15:39:00

## Создадим общий датафрейм

In [9]:
# Создадим один общий датафрейм:
joined_df = df_tasks.set_index('USER_ID').join([df_users.set_index('USER_ID')])

# Сбросим индекс итоговой таблицы:
joined_df = joined_df.reset_index() # Напишите ваш код здесь

In [10]:
display(joined_df)

,USER_ID,TASK_ID,CLIENT_ID,STATUS,START_DATE,END_DATE,LAST_NAME,START_WORK,END_WORK
0,79,3,2159,fail,2026-01-13 13:58:20,2026-01-29 18:20:21,GALKIN,13,21
1,66,4,2527,success,2026-02-18 10:40:42,2026-02-18 10:47:38,Larionov,3,0
2,473,5,659,fail,2026-01-04 06:34:41,2026-01-24 12:34:14,Gazmanov,7,7
3,351,6,764,success,2026-01-11 18:00:30,2026-01-28 04:50:16,Fedotov,21,6
4,396,7,3122,success,2026-02-17 02:54:07,2026-02-22 10:42:03,Evseev,1,8
...,...,...,...,...,...,...,...,...,...
8997,102,9000,4035,success,2026-01-23 23:20:31,2026-01-31 14:59:51,Seleznev,12,6
8998,368,9001,3970,success,2026-01-29 00:56:45,2026-02-12 21:15:21,Dmitriev,14,17
8999,336,9002,1941,success,2026-01-23 15:50:04,2026-02-20 19:30:40,Anisimov,8,11
9000,1,1,1,success,2023-05-01 09:17:00,2023-05-21 17:23:00,Ivanov,8,19
9001,1,2,2,fail,2023-05-01 10:19:00,2023-05-21 15:39:00,Ivanov,8,19

#### Проверяем объединение

In [11]:
# 1) 9002 записи - кол-во записей не увеличилось
joined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9002 entries, 0 to 9001
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   USER_ID     9002 non-null   int64
 1   TASK_ID     9002 non-null   int64
 2   CLIENT_ID   9002 non-null   int64
 3   STATUS      9002 non-null   object
 4   START_DATE  9002 non-null   object
 5   END_DATE    9002 non-null   object
 6   LAST_NAME   9002 non-null   object
 7   START_WORK  9002 non-null   int64
 8   END_WORK    9002 non-null   int64
dtypes: int64(5), object(4)
memory usage: 633.1+ KB

In [12]:
# 2) Подсчитаем количество строк с данными для каждого столбца датафрейма:
print(joined_df.count())

USER_ID       9002
TASK_ID       9002
CLIENT_ID     9002
STATUS        9002
START_DATE    9002
END_DATE      9002
LAST_NAME     9002
START_WORK    9002
END_WORK      9002
dtype: int64

In [13]:
# Подсчитаем количество строк с пропусками:
print(joined_df.shape[0] - joined_df.count())

USER_ID       0
TASK_ID       0
CLIENT_ID     0
STATUS        0
START_DATE    0
END_DATE      0
LAST_NAME     0
START_WORK    0
END_WORK      0
dtype: int64

#### Пропусков в данных не обнаружено. Кол-во TASK_ID не изменилось

In [14]:
joined_df = joined_df.set_index('CLIENT_ID').join([df_clients.set_index('CLIENT_ID')])

# Сбросим индекс итоговой таблицы:
joined_df = joined_df.reset_index() # Напишите ваш код здесь

#### Проверяем объединение

In [15]:
# 1) 9002 записи - кол-во записей не увеличилось
joined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9002 entries, 0 to 9001
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CLIENT_ID   9002 non-null   int64
 1   USER_ID     9002 non-null   int64
 2   TASK_ID     9002 non-null   int64
 3   STATUS      9002 non-null   object
 4   START_DATE  9002 non-null   object
 5   END_DATE    9002 non-null   object
 6   LAST_NAME   9002 non-null   object
 7   START_WORK  9002 non-null   int64
 8   END_WORK    9002 non-null   int64
 9   NAME        9002 non-null   object
 10  CATEGORY    9002 non-null   object
dtypes: int64(5), object(6)
memory usage: 773.7+ KB

In [16]:
# Подсчитаем количество строк с пропусками:
print(joined_df.shape[0] - joined_df.count())

CLIENT_ID     0
USER_ID       0
TASK_ID       0
STATUS        0
START_DATE    0
END_DATE      0
LAST_NAME     0
START_WORK    0
END_WORK      0
NAME          0
CATEGORY      0
dtype: int64

In [17]:
display(joined_df)

,CLIENT_ID,USER_ID,TASK_ID,STATUS,START_DATE,END_DATE,LAST_NAME,START_WORK,END_WORK,NAME,CATEGORY
0,2159,79,3,fail,2026-01-13 13:58:20,2026-01-29 18:20:21,GALKIN,13,21,ЗАО Колесникова,Средний бизнес
1,2527,66,4,success,2026-02-18 10:40:42,2026-02-18 10:47:38,Larionov,3,0,АО Богданов Агафонова,Малый бизнес
2,659,473,5,fail,2026-01-04 06:34:41,2026-01-24 12:34:14,Gazmanov,7,7,Носова Инкорпорэйтед,Средний бизнес
3,764,351,6,success,2026-01-11 18:00:30,2026-01-28 04:50:16,Fedotov,21,6,АО Силина-Русаков,Малый бизнес
4,3122,396,7,success,2026-02-17 02:54:07,2026-02-22 10:42:03,Evseev,1,8,АО Исаев Прохорова,Малый бизнес
...,...,...,...,...,...,...,...,...,...,...,...
8997,4035,102,9000,success,2026-01-23 23:20:31,2026-01-31 14:59:51,Seleznev,12,6,Сергеева и партнеры,Средний бизнес
8998,3970,368,9001,success,2026-01-29 00:56:45,2026-02-12 21:15:21,Dmitriev,14,17,РАО Аксенова-Дементьева,Средний бизнес
8999,1941,336,9002,success,2026-01-23 15:50:04,2026-02-20 19:30:40,Anisimov,8,11,НПО Мухин,Средний бизнес
9000,1,1,1,success,2023-05-01 09:17:00,2023-05-21 17:23:00,Ivanov,8,19,ИП Шолохов,Малый бизнес
9001,2,1,2,fail,2023-05-01 10:19:00,2023-05-21 15:39:00,Ivanov,8,19,ООО Звездочка,Средний бизнес

### Промежуточные результаты мы уже посчитали в базе данных

In [18]:
# SELECT count(distinct "TASK_ID") FROM test.tasks
# where "STATUS" = 'success'; -- 4435

# SELECT count(distinct "TASK_ID") FROM test.tasks; -- 9002

# SELECT
# (SUM(CASE WHEN "STATUS" = 'success' THEN 1 ELSE 0 END) / COUNT(DISTINCT "TASK_ID")::float) * 100
# FROM test.tasks; -- 49.26%

### Требуется проверить, что после объединения результаты не изменились

In [19]:
result = joined_df.query('STATUS == "success"').count()

In [20]:
print(result) # Ожидаемый результат 4435

CLIENT_ID     4435
USER_ID       4435
TASK_ID       4435
STATUS        4435
START_DATE    4435
END_DATE      4435
LAST_NAME     4435
START_WORK    4435
END_WORK      4435
NAME          4435
CATEGORY      4435
dtype: int64

In [21]:
print((result / joined_df.count()) * 100) # Ожидаемый результат 49.26683

CLIENT_ID    49.267
USER_ID      49.267
TASK_ID      49.267
STATUS       49.267
START_DATE   49.267
END_DATE     49.267
LAST_NAME    49.267
START_WORK   49.267
END_WORK     49.267
NAME         49.267
CATEGORY     49.267
dtype: float64

In [22]:
# Создадим дубликат нашего объединённого датафрейма, чтобы была возможность восстановить данные в любой момент
df = joined_df.copy()

In [23]:
df.head()

,CLIENT_ID,USER_ID,TASK_ID,STATUS,START_DATE,END_DATE,LAST_NAME,START_WORK,END_WORK,NAME,CATEGORY
0,2159,79,3,fail,2026-01-13 13:58:20,2026-01-29 18:20:21,GALKIN,13,21,ЗАО Колесникова,Средний бизнес
1,2527,66,4,success,2026-02-18 10:40:42,2026-02-18 10:47:38,Larionov,3,0,АО Богданов Агафонова,Малый бизнес
2,659,473,5,fail,2026-01-04 06:34:41,2026-01-24 12:34:14,Gazmanov,7,7,Носова Инкорпорэйтед,Средний бизнес
3,764,351,6,success,2026-01-11 18:00:30,2026-01-28 04:50:16,Fedotov,21,6,АО Силина-Русаков,Малый бизнес
4,3122,396,7,success,2026-02-17 02:54:07,2026-02-22 10:42:03,Evseev,1,8,АО Исаев Прохорова,Малый бизнес

## Задания № 1:
### Топ-5 фамилий менеджеров по доли успешно закрытых задач

In [24]:
# От себя добавлю, что нам требуется вывести "топ 5 фамилий менеджеров по доли успешно закрытых задач"

In [25]:
# Т.е. кол-во успешно выполненных задач у USER_ID к общему кол-ву задач USER_ID

In [26]:
users_analysis = df[['USER_ID', 'TASK_ID', 'STATUS', 'LAST_NAME']]

In [27]:
# Подсчитаем долю пользователей, прослушавших композиции стиля funk:
df_success_users = users_analysis.query('STATUS == "success"')[['USER_ID', 'TASK_ID', 'STATUS', 'LAST_NAME']]

# Переименуем столбец TASK_ID, чтобы не запустаться в данных
df_success_users.rename(columns={'TASK_ID': 'SUCCESS_TASK_ID'}, inplace=True)

df_success_users.reset_index()

      index  USER_ID  SUCCESS_TASK_ID   STATUS  LAST_NAME
0         1       66                4  success   Larionov
1         3      351                6  success    Fedotov
2         4      396                7  success     Evseev
3         6      195                9  success   Kirillov
4         7      108               10  success      Zueva
...     ...      ...              ...      ...        ...
4430   8996       71             8999  success  Litvinova
4431   8997      102             9000  success   Seleznev
4432   8998      368             9001  success   Dmitriev
4433   8999      336             9002  success   Anisimov
4434   9000        1                1  success     Ivanov

[4435 rows x 5 columns]

In [28]:
print(df_success_users)

      USER_ID  SUCCESS_TASK_ID   STATUS  LAST_NAME
1          66                4  success   Larionov
3         351                6  success    Fedotov
4         396                7  success     Evseev
6         195                9  success   Kirillov
7         108               10  success      Zueva
...       ...              ...      ...        ...
8996       71             8999  success  Litvinova
8997      102             9000  success   Seleznev
8998      368             9001  success   Dmitriev
8999      336             9002  success   Anisimov
9000        1                1  success     Ivanov

[4435 rows x 4 columns]

In [29]:
# Посчитаем кол-во успешных задач для каждого пользователя
df_success_users = df_success_users.groupby('USER_ID').agg({'SUCCESS_TASK_ID':'count'})
print(df_success_users)

         SUCCESS_TASK_ID
USER_ID
1                      9
2                      7
3                     12
4                     10
5                     15
...                  ...
495                   10
496                    4
497                   10
498                   10
499                    4

[499 rows x 1 columns]

In [30]:
# Посчитаем общее кол-во задач для каждого user_id
df_total_users = users_analysis.groupby('USER_ID').agg({'TASK_ID':'count'})
# Переименуем столбец TASK_ID, чтобы не запустаться в данных
df_total_users.rename(columns={'TASK_ID': 'TOTAL_TASK_ID'}, inplace=True)

df_total_users.reset_index()

print(df_total_users)

         TOTAL_TASK_ID
USER_ID
1                   22
2                   13
3                   21
4                   18
5                   21
...                ...
495                 17
496                 13
497                 18
498                 23
499                 11

[499 rows x 1 columns]

In [31]:
# Или с указанием типа объединения
joined_users_df = pd.merge(df_total_users, df_success_users, on='USER_ID', how='left').reset_index()

In [32]:
print(joined_users_df)

     USER_ID  TOTAL_TASK_ID  SUCCESS_TASK_ID
0          1             22                9
1          2             13                7
2          3             21               12
3          4             18               10
4          5             21               15
..       ...            ...              ...
494      495             17               10
495      496             13                4
496      497             18               10
497      498             23               10
498      499             11                4

[499 rows x 3 columns]

In [33]:
# Создадим столбец SUCCESS_RATE, где будет расчет процента успешных задач для каждого USER_ID
joined_users_df['SUCCESS_RATE'] = (
    joined_users_df['SUCCESS_TASK_ID'] / joined_users_df['TOTAL_TASK_ID'] * 100
).round(2)

In [34]:
joined_users_df = joined_users_df.sort_values(by='SUCCESS_RATE', ascending=False)

In [35]:
# Добавим Фамилию пользователя для нагладности
last_name_df = df_users[['USER_ID', 'LAST_NAME']].copy()

joined_users_df = pd.merge(
    joined_users_df, 
    last_name_df,
    on='USER_ID', 
    how='inner'
).reset_index(drop=True)  # drop=True чтобы не добавлять старый индекс как столбец

## Топ-5 фамилий менеджеров по доли успешно закрытых задач

In [36]:
joined_users_df.head(5)

   USER_ID  TOTAL_TASK_ID  SUCCESS_TASK_ID  SUCCESS_RATE  LAST_NAME
0      432             16               14        87.500   Kulikova
1       38             15               13        86.670  Gavrilova
2       90             13               11        84.620   Zakharov
3      337             12               10        83.330  Sitnikova
4      232             17               14        82.350    Rozhkov

## Задания № 2:
### Собрать фамилии менеджеров у кого показатели отработки задач (% неуспешных задач) по одной из категорий бизнеса хуже, чем в среднем у всех менеджеров по всем категориям.

In [37]:
print(df.head())

   CLIENT_ID  USER_ID  TASK_ID   STATUS           START_DATE  \
0       2159       79        3     fail  2026-01-13 13:58:20
1       2527       66        4  success  2026-02-18 10:40:42
2        659      473        5     fail  2026-01-04 06:34:41
3        764      351        6  success  2026-01-11 18:00:30
4       3122      396        7  success  2026-02-17 02:54:07

              END_DATE LAST_NAME  START_WORK  END_WORK                   NAME  \
0  2026-01-29 18:20:21    GALKIN          13        21        ЗАО Колесникова
1  2026-02-18 10:47:38  Larionov           3         0  АО Богданов Агафонова
2  2026-01-24 12:34:14  Gazmanov           7         7   Носова Инкорпорэйтед
3  2026-01-28 04:50:16   Fedotov          21         6      АО Силина-Русаков
4  2026-02-22 10:42:03    Evseev           1         8     АО Исаев Прохорова

         CATEGORY
0  Средний бизнес
1    Малый бизнес
2  Средний бизнес
3    Малый бизнес
4    Малый бизнес

In [38]:
# Подсчитываем количество неуспешных задач по каждой категории для каждого пользователя
unsuccess_df = df.query("STATUS == 'fail'").groupby(['USER_ID', 'CATEGORY']).agg({'TASK_ID': 'count'}).rename(columns={'TASK_ID': 'FAILED_TASKS'})

In [39]:
print(unsuccess_df)

                        FAILED_TASKS
USER_ID CATEGORY
1       Малый бизнес               6
        Средний бизнес             7
2       Малый бизнес               2
        Средний бизнес             4
3       Малый бизнес               1
...                              ...
497     Средний бизнес             5
498     Малый бизнес               7
        Средний бизнес             6
499     Малый бизнес               3
        Средний бизнес             4

[985 rows x 1 columns]

In [40]:
# Подсчитываем общее количество задач
total_tasks = df.groupby(['USER_ID', 'CATEGORY']).agg({'TASK_ID': 'count'}).rename(columns={'TASK_ID': 'TOTAL_TASKS'})

In [41]:
print(total_tasks)

                        TOTAL_TASKS
USER_ID CATEGORY
1       Малый бизнес             10
        Средний бизнес           12
2       Малый бизнес              5
        Средний бизнес            8
3       Малый бизнес              5
...                             ...
497     Средний бизнес           12
498     Малый бизнес             12
        Средний бизнес           11
499     Малый бизнес              4
        Средний бизнес            7

[998 rows x 1 columns]

In [42]:
# самопроверка
print(df.query("USER_ID == 1 and STATUS == 'fail'").groupby(['USER_ID', 'CATEGORY']).agg({'TASK_ID': 'count'}))
print('-----------------------------------------------')
print(df.query("USER_ID == 1").groupby(['USER_ID', 'CATEGORY']).agg({'TASK_ID': 'count'}))

                        TASK_ID
USER_ID CATEGORY
1       Малый бизнес          6
        Средний бизнес        7
-----------------------------------------------
                        TASK_ID
USER_ID CATEGORY
1       Малый бизнес         10
        Средний бизнес       12

In [43]:
# Объединяем результаты
result = unsuccess_df.join(total_tasks)

# Рассчитываем процент неуспешных задач
result['FAILURE_RATE'] = result['FAILED_TASKS'] / result['TOTAL_TASKS'] * 100

# Сбрасываем индекс, если нужно получить привычный DataFrame
result = result.reset_index()

# Выводим результат
print(result)

     USER_ID        CATEGORY  FAILED_TASKS  TOTAL_TASKS  FAILURE_RATE
0          1    Малый бизнес             6           10        60.000
1          1  Средний бизнес             7           12        58.333
2          2    Малый бизнес             2            5        40.000
3          2  Средний бизнес             4            8        50.000
4          3    Малый бизнес             1            5        20.000
..       ...             ...           ...          ...           ...
980      497  Средний бизнес             5           12        41.667
981      498    Малый бизнес             7           12        58.333
982      498  Средний бизнес             6           11        54.545
983      499    Малый бизнес             3            4        75.000
984      499  Средний бизнес             4            7        57.143

[985 rows x 5 columns]

In [44]:
# Группировка по категории и вычисление среднего
avg_per_category = result.groupby('CATEGORY')['FAILURE_RATE'].mean().reset_index()
avg_per_category.columns = ['CATEGORY', 'MEAN_FAILURE_RATE']

In [45]:
display(avg_per_category)

         CATEGORY  MEAN_FAILURE_RATE
0    Малый бизнес             51.617
1  Средний бизнес             50.652

In [46]:
# Объединяем средние с исходными данными для сравнения
result = pd.merge(result, avg_per_category, on='CATEGORY')
result['LESS_MEAN'] = result['FAILURE_RATE'] > result['MEAN_FAILURE_RATE']

# Получаем фамилии менеджеров, чьи показатели хуже среднего
df_less_mean = result[result['LESS_MEAN']][['USER_ID', 'CATEGORY', 'FAILURE_RATE', 'MEAN_FAILURE_RATE', 'LESS_MEAN']]

In [47]:
display(df_less_mean)

     USER_ID        CATEGORY  FAILURE_RATE  MEAN_FAILURE_RATE  LESS_MEAN
0          1    Малый бизнес        60.000             51.617       True
1          1  Средний бизнес        58.333             50.652       True
6          4    Малый бизнес        54.545             51.617       True
11         6  Средний бизнес        57.143             50.652       True
13         7  Средний бизнес        64.286             50.652       True
..       ...             ...           ...                ...        ...
978      496  Средний бизнес        66.667             50.652       True
981      498    Малый бизнес        58.333             51.617       True
982      498  Средний бизнес        54.545             50.652       True
983      499    Малый бизнес        75.000             51.617       True
984      499  Средний бизнес        57.143             50.652       True

[452 rows x 5 columns]

In [48]:
# Добавим Фамилию пользователя для нагладности
df_less_mean = pd.merge(
    df_less_mean, 
    last_name_df,
    on='USER_ID', 
    how='inner'
).reset_index(drop=True)  # drop=True чтобы не добавлять старый индекс как столбец

In [49]:
df_less_mean = df_less_mean[['USER_ID', 'LAST_NAME']].drop_duplicates().reset_index(drop=True)

### Выполним поставленную задачу и выведем Фамилии пользователей. Добавим ID пользователя, так как Фамилии не уникальны

In [50]:
print("Уникальные ID и Фамилии:")
df_less_mean.head(15)

Уникальные ID и Фамилии:

    USER_ID   LAST_NAME
0         1      Ivanov
1         4  Molchanova
2         6   Filippova
3         7      Kostin
4         9  University
5        10     Blinova
6        12    Matveeva
7        14    Drozdova
8        15   Kosheleva
9        16   Anisimova
10       17      Bykova
11       18   Gorshkova
12       20     Simonov
13       21    Nikitina
14       22     Evseeva

## Задания № 3:
### Реализовать задание № 2 на Python - выполнено

## Задания № 4:
### Генерация гипотез/идей. По каким открытым/банковским данным можно понять,  что клиент ведет внешнеэкономическую деятельность?

### Вариант № 1) Сайт https://www.tks.ru/

In [51]:
### Все детали — от функционала ПО до перечня клиентов — однозначно указывают на то, что заказчики компании участвуют во внешнеторговых операциях (импорте/экспорте товаров и услуг)
### На сайте представлены различные базы данных с детализацией до номера телефона контрагента

# База данных Таможенные представители 
# АО ВЭД АГЕНТ
# Регистрационный номер
# 1423 от 20 декабря 2021 г.
# Наименование
# АО ВЭД АГЕНТ
# Адрес
# 630005, Новосибирская обл, Новосибирск г, Ольги Жилиной ул, д. 33, кв. 105
# ИНН
# 5404454954
# КПП
# 540601001
# Телефон
# +7 (383) 207-91-05
# Адрес эл. почты
# info@vedagent.ru
# Наименование филиала
# Обособленное подразделение АО ВЭД АГЕНТ
# Адрес филиала
# 630078, Новосибирская обл., г. Новосибирск, пл. имени Карла Маркса, 7, 1008
# КПП филиала
# 540445001

### Используя библиотеку BeautifulSoup можно осуществить парминг данных прямо с сайта www.tks.ru

In [52]:
# Карточка контрагента лежит в <div class="database-card__content">

In [53]:
import requests
from bs4 import BeautifulSoup

# URL для парсинга
url = 'https://www.tks.ru/db/carrier/1183/'

# Получаем HTML-код страницы
response = requests.get(url)

# Проверяем, что запрос успешен
if response.status_code == 200:
    # Парсим HTML-код
    soup = BeautifulSoup(response.text, 'html.parser')

    # Пример: найти заголовок страницы
    title = soup.find('title').text
    print(f'Заголовок страницы: {title}')

    # найти все элементы страницы
    data = soup.find_all('div', class_='database-card__content')
    for item in data:
        print(item.text.strip())  # Выводим карточку партнера
else:
    print(f'Ошибка при запросе страницы: {response.status_code}')

Заголовок страницы: Перевозчик "АО "АВТО-ХОЛДИНГ"", лиц. 10000/0443 - база данных Перевозчики /
Страна
Российская Федерация


Лицензия
10000/0443


Владелец
АО "АВТО-ХОЛДИНГ"


ИНН
7814080664


КПП
781101001


ОГРН
1027807587543


ОКПО
47928330


Адрес владельца
192177, г. Санкт-Петербург, вн. тер. г. муниципальный округ Рыбацкое, дор На Петро-Славянку, д. 7, литера Ф. помещ. 2-Н, офис 2.3


Телефон
(812) 700-52-27


Код таможни


                                    10000000/90000




Наименование таможни
ФЕДЕРАЛЬНАЯ ТАМОЖЕННАЯ СЛУЖБА


Виды транспорта
Автодорожный транспорт

### Используя библиотеку BeautifulSoup можно осуществить парминг данных прямо с сайта www.rbc.ru

In [54]:
import requests
from bs4 import BeautifulSoup

# URL для парсинга
url = 'https://companies.rbc.ru/search/?category_id=542'

# Отправляем GET-запрос к странице
response = requests.get(url)

# Проверяем успешность запроса
if response.status_code == 200:
    # Парсим контент страницы с помощью BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Ищем все элементы, содержащие информацию о компаниях
    # Необходимо уточнить, какие именно теги и атрибуты содержат нужную информацию
    company_element = soup.find('a', class_='company-name-highlight')
    if company_element:
        company_name = company_element.get_text()
    else:
        company_name = None
    category = soup.find('div', class_='category-breadcrumb').find('span', class_='category-breadcrumb__item').text
    link = soup.find('a', class_='company-name-highlight')['href']
    # Здесь измените селектор, если необходимо
    # Вывод результатов
    print(f"Наименование компании: {company_name}")
    print(f"Категория: {category}")
    print(f"Ссылка: {link}")

else:
    print(f'Ошибка при запросе: {response.status_code}')

Наименование компании: ГК «Сладкая жизнь»
Категория: Оптовая торговля
Ссылка: https://companies.rbc.ru/id/1055233034845-gk-sladkaya-zhizn/